const fs = require("fs");
const path = require("path");
function read(file,fallback){try{return JSON.parse(fs.readFileSync(file,"utf8"));}catch{return fallback;}}
function write(file,value){fs.mkdirSync(path.dirname(file),{recursive:true});const tmp=`${file}.tmp-${process.pid}-${Date.now()}`;fs.writeFileSync(tmp,JSON.stringify(value,null,2),"utf8");fs.renameSync(tmp,file);}
function text(v,f="",m=240){const s=String(v??"").replace(/[\0\r\n\t]+/g," ").replace(/\s+/g," ").trim();return (s||f).slice(0,m);}
function id(v){return String(v??"").replace(/[^a-zA-Z0-9._-]/g,"-").replace(/-+/g,"-").replace(/^-|-$/g,"").slice(0,96);}
function num(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}
function section(s={},i=0){const start=Math.max(0,num(s.startMs));return {id:id(s.id)||`section-${i+1}`,type:text(s.type,"unknown",48),name:text(s.name,s.type||`Section ${i+1}`,120),startMs:start,endMs:Math.max(start,num(s.endMs,start)),confidence:Math.max(0,Math.min(1,num(s.confidence))),source:text(s.source,"manual",48)};}
function sanitize(input={},existing=null){const now=new Date().toISOString();const pid=id(input.id)||id(existing?.id)||`ums-${Date.now()}`;return {schema:"uaos.music-scene",schemaVersion:"0.1.0",id:pid,metadata:{title:text(input?.metadata?.title||input.title,"Untitled",160),artist:text(input?.metadata?.artist||input.artist,"",160),durationMs:Math.max(0,num(input?.metadata?.durationMs??input.durationMs)),sourceFileName:text(input?.metadata?.sourceFileName||input.sourceFileName,"",240),sourceMimeType:text(input?.metadata?.sourceMimeType||input.sourceMimeType,"",120),sourceSize:Math.max(0,num(input?.metadata?.sourceSize??input.sourceSize)),createdAt:text(existing?.metadata?.createdAt||input?.metadata?.createdAt,now,64),updatedAt:now},rights:{category:"user-private-project",ownershipConfirmed:input?.rights?.ownershipConfirmed===true,commercialUseAllowed:input?.rights?.commercialUseAllowed===true,trainingAllowed:false,provenance:[]},timeline:{tempoMap:[{tick:0,bpm:120,confidence:0}],timeSignatures:[{tick:0,numerator:4,denominator:4}],sections:Array.isArray(input?.timeline?.sections)?input.timeline.sections.slice(0,256).map(section):[]},harmony:{key:null,chords:[],maqam:null,ajnas:[],modulations:[],quarterToneSystem:null},tracks:Array.isArray(input?.tracks)?input.tracks.slice(0,64):[],automation:[],deviceMappings:[],analysis:{status:"not-analyzed",providers:[],confidence:{},warnings:["No AI analysis has been executed. Sections are manual."]},versions:Array.isArray(existing?.versions)?[...existing.versions.slice(-49),{version:existing.versions.length+1,createdAt:now,reason:"project-saved"}]:[{version:1,createdAt:now,reason:"project-created"}]};}
function createUmsRouter(express,options={}){const router=express.Router();const dataDir=options.dataDir||path.join(__dirname,"data");const file=path.join(dataDir,"ums-projects.json");if(!fs.existsSync(file))write(file,[]);
router.get('/status',(_q,r)=>r.json({ok:true,feature:'smart-sequencer-vslice1',capabilities:{metadata:true,manualSections:true,persistence:true,aiAnalysis:false,stems:false,maqam:false,midiExport:false}}));
router.get('/projects',(_q,r)=>{const p=read(file,[]);r.json({ok:true,projects:p.map(x=>({id:x.id,title:x.metadata?.title||'Untitled',artist:x.metadata?.artist||'',sourceFileName:x.metadata?.sourceFileName||'',durationMs:x.metadata?.durationMs||0,updatedAt:x.metadata?.updatedAt||null,sectionCount:x.timeline?.sections?.length||0,trackCount:x.tracks?.length||0,analysisStatus:x.analysis?.status||'not-analyzed'}))});});
router.get('/projects/:id',(q,r)=>{const p=read(file,[]).find(x=>x.id===id(q.params.id));return p?r.json({ok:true,project:p}):r.status(404).json({ok:false,error:'UMS project not found.'});});
router.post('/projects',(q,r)=>{const all=read(file,[]),p=sanitize(q.body||{});if(all.some(x=>x.id===p.id))return r.status(409).json({ok:false,error:'UMS project already exists.'});all.push(p);write(file,all);return r.status(201).json({ok:true,project:p});});
router.put('/projects/:id',(q,r)=>{const all=read(file,[]),pid=id(q.params.id),i=all.findIndex(x=>x.id===pid);if(i<0)return r.status(404).json({ok:false,error:'UMS project not found.'});const p=sanitize({...q.body,id:pid},all[i]);all[i]=p;write(file,all);return r.json({ok:true,project:p});});
return router;}
module.exports={createUmsRouter,sanitizeProject:sanitize};
