param(
  [switch]$AllowWorkingChanges
)

$ErrorActionPreference = "Stop"
$root = Resolve-Path (Join-Path $PSScriptRoot "..")
$reportPath = Join-Path $root "reports/UAOS_LOCAL_QA_CHECK_REPORT.md"
$checks = New-Object System.Collections.Generic.List[object]

function Add-Check($Name, $Status, $Detail) {
  $script:checks.Add([pscustomobject]@{
    Name = $Name
    Status = $Status
    Detail = $Detail
  })
}

Push-Location $root
try {
  $gitStatus = git status --short
  if ($gitStatus -and -not $AllowWorkingChanges) {
    Add-Check "Git clean" "FAIL" "Working tree has changes."
  } elseif ($gitStatus -and $AllowWorkingChanges) {
    Add-Check "Git clean" "WARN" "Working changes allowed for report generation before commit."
  } else {
    Add-Check "Git clean" "PASS" "Working tree clean."
  }

  Push-Location (Join-Path $root "frontend")
  try {
    npm run build | Out-Null
    Add-Check "Frontend build" "PASS" "npm run build completed."
  } catch {
    Add-Check "Frontend build" "FAIL" $_.Exception.Message
  } finally {
    Pop-Location
  }

  $requiredPaths = @(
    "generated/UAOS_AUDIENCE_SEPARATION_FIREWALL_V1/UAOS_TESTER_ISOLATED_PACK_V1.zip",
    "generated/UAOS_AUDIENCE_SEPARATION_FIREWALL_V1/UAOS_JOBCENTER_ISOLATED_PACK_V1.zip",
    "generated/UAOS_AUDIENCE_SEPARATION_FIREWALL_V1/UAOS_FRIEND_ISOLATED_PACK_V1.zip",
    "generated/library-factory",
    "generated/jampler-programs",
    "generated/project-templates",
    "generated/pixi/pixi-knowledge-pack.json",
    "reports/UAOS_AUDIENCE_SEPARATION_FIREWALL_V1_REPORT.md"
  )

  foreach ($path in $requiredPaths) {
    if (Test-Path (Join-Path $root $path)) {
      Add-Check "Required path: $path" "PASS" "Found."
    } else {
      Add-Check "Required path: $path" "FAIL" "Missing."
    }
  }

  $forbiddenExtensions = @(".STY", ".SET", ".PRS", ".STL", ".PAT", ".MSP", ".KST")
  $writerOutputs = Get-ChildItem (Join-Path $root "generated") -Recurse -File -ErrorAction SilentlyContinue |
    Where-Object { $forbiddenExtensions -contains $_.Extension.ToUpperInvariant() }
  if ($writerOutputs.Count -eq 0) {
    Add-Check "Forbidden writer outputs" "PASS" "No .STY/.SET/.PRS/.STL/.PAT/.MSP/.KST files found under generated."
  } else {
    Add-Check "Forbidden writer outputs" "FAIL" ($writerOutputs.FullName -join "; ")
  }

  $realWriterText = rg -n -i "deviceWriterEnabled[^a-zA-Z0-9]+true|realKeyboardOutputEnabled[^a-zA-Z0-9]+true|commercialFinalClaim[^a-zA-Z0-9]+true|realDeviceWriter[^a-zA-Z0-9]+ENABLED" generated reports frontend/src 2>$null
  if ($LASTEXITCODE -eq 1) {
    Add-Check "Unsafe claim scan" "PASS" "No unsafe enabled/final claim text found."
  } else {
    Add-Check "Unsafe claim scan" "FAIL" "Potential unsafe claim text found."
  }

  Add-Check "Vercel action" "PASS" "This QA script does not run Vercel or public publish commands."
  Add-Check "Release folder" "PASS" "This QA script does not modify release/."

  $failed = $checks | Where-Object { $_.Status -eq "FAIL" }
  $lines = @(
    "# UAOS Local QA Check Report",
    "",
    "Date: 2026-06-28",
    "Mode: $(if ($AllowWorkingChanges) { 'pre-commit report generation' } else { 'strict clean check' })",
    "",
    "## Summary",
    "",
    "Status: $(if ($failed.Count -eq 0) { 'PASS' } else { 'FAIL' })",
    "",
    "## Checks",
    ""
  )

  foreach ($check in $checks) {
    $lines += "- [$($check.Status)] $($check.Name) - $($check.Detail)"
  }

  $lines += ""
  $lines += "## Safety"
  $lines += ""
  $lines += "- No Vercel command is run."
  $lines += "- No public publish command is run."
  $lines += "- No device writer is enabled."
  $lines += "- No real keyboard output is enabled."
  $lines += "- No forbidden writer output extension is generated by this script."

  Set-Content -LiteralPath $reportPath -Value $lines
  if ($failed.Count -gt 0) {
    exit 1
  }
} finally {
  Pop-Location
}
